import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  lobbyContainer: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "80vw",
    height: "80vh",
    backgroundColor: "#F7F7EF",
    borderRadius: "25px",
    padding: theme.spacing(3),
    display: "flex",
    flexDirection: "column",
  },
  titleContainer: {
    flex: 1,
    width: "100%",
    height: "15%",
    backgroundColor: "#F3D388",
    borderRadius: "25px 25px 0 0",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: theme.spacing(5),
  },
  path: {
    backgroundColor: "#181C1F",
    opacity: "0.05",
    height: "10px",
    width: "100%",
    margin: `${theme.spacing(3)}px 0`,
  },
  title: {
    color: "#171B1E",
    fontSize: "calc(2vh + 2vw)",
    fontWeight: "bold",
    margin: 0,
    textAlign: "left",
  },
  lobbyCodeContainer: {
    backgroundColor: "#171B1E",
    borderRadius: "25px",
    stroke: "#707070",
    display: "flex",
    justifyContent: "flex-end",
    flexDirection: "row",
    alignItems: "right",
    padding: theme.spacing(2),
    width: "25%",
  },
  lobbyCode: {
    flex: 1,
    color: "#F7F7EF",
    fontSize: "calc(1vh + 1vw)",
    fontWeight: "bold",
    margin: 10,
    textAlign: "left",
  },
  backIcon: {
    width: "79.17px",
    height: "54.81px",
    transform: "rotate(180deg)",
    fill: "#181C1F",
    alignItems: "right",
  },
  lobbyMain: {
    flex: 3,
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: "85%",
  },
  playerListContainer: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    width: "50%",
    height: "100%",
    borderRadius: "40px 0 0 40%",
    backgroundColor: "#FFFFFF",
    padding: theme.spacing(3),
  },
  textPlayers: {
    fontSize: "calc(1vh + 1vw)",
    fontWeight: "normal",
    color: "#171B1E",
    textAlign: "left",
    width: "176px",
    height: "48px",
    margin: 0,
  },
  playerButtonContainer: {
    display: "flex",
    alignItems: "center",
    width: "190%",
    height: "60px",
    backgroundColor: "#171B1E",
    borderRadius: "15px",
    marginBottom: theme.spacing(1),
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
  },
  circle: {
    width: "23px",
    height: "24px",
    backgroundColor: "#F3D388",
    borderRadius: "50%",
    marginRight: theme.spacing(2),
  },
  playerName: {
    width: "116px",
    height: "24px",
    color: "#F7F7EF",
    fontSize: "20px",
    fontWeight: "normal",
    textAlign: "right",
    margin: 0,
  },
  textSettings: {
    fontSize: "calc(1vh + 1vw)",
    fontWeight: "normal",
    color: "#171B1E",
    textAlign: "left",
    width: "176px",
    height: "48px",
    margin: 0,
  },
  settingsContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: "50%",
    height: "100%",
    borderRadius: "40px 0 0 40%",
    backgroundColor: "#FFFFFF",
    padding: theme.spacing(3),
  },
  settingsLeft:{
    floats:"left",
    width: "50%",
    display: "flex",
    flexDirection: "column",
    marginRight: theme.spacing(3),
  },
  modifyVideoPoolContainer: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "30%",
    borderRadius: "15px",
    backgroundColor: theme.palette.background.paper,
    boxShadow: "0px 0px 20px rgba(0, 0, 0, 0.25)",
    padding: theme.spacing(3),
    marginTop: theme.spacing(3),
  },
  modifyVideoPoolTitle: {
    fontWeight: "bold",
    marginBottom: theme.spacing(2),
    fontSize: "1.5rem",
  },
  modifyVideoPoolContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
    height: "50%",
    width: "100%",
  },
  languageSettingContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "5%",
    border: "1px solid #D5DDDC",
    borderRadius: "15px",
    marginTop: theme.spacing(3),
    padding: theme.spacing(2),
  },
  languageSettingTitle: {
    fontWeight: "bold",
    marginBottom: theme.spacing(1),
    fontSize: "1.5rem",
    color: "#F7F7EF",
  },
  playlistInputContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "5%",
    borderRadius: "15px",
    backgroundColor: "#FFFFFF",
    marginTop: theme.spacing(3),
    padding: theme.spacing(2),
  },
  languageDropdownContainer: {
    position: "absolute",
    top: "15%",
    right: "5%",
    width: "15%",
    height: "10%",
    borderRadius: "13px",
    backgroundColor: "#ECC873",
  },
  languageDropdownButton: {
    position: "absolute",
    top: "52%",
    right: "10%",
    width: "3%",
    height: "3%",
    backgroundColor: "#181C1F",
  },
  playersContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "30%",
    marginTop: theme.spacing(3),
  },
  playersTitleContainer: {
    fontWeight: "bold",
    marginBottom: theme.spacing(2),
    fontSize: "1.5rem",
    backgroundColor: "#171B1E",
    color: "#F7F7EF",
    padding: theme.spacing(2),
    borderRadius: "15px",
    width: "100%",
  },
  playerSettingsContainer: {
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(2),
  },
  playerSettingsTitle: {
    fontSize: "1.2rem",
    fontWeight: "bold",
    marginBottom: theme.spacing(2),
  },
  playerSettingsInputContainer: {
    display: "flex",
    alignItems: "center",
    marginBottom: theme.spacing(2),
  },
  playerSettingsInputLabel: {
    fontWeight: "bold",
    marginRight: theme.spacing(2),
  },
  playerSettingsInput: {
    width: "50%",
    marginRight: theme.spacing(2),
  },
  onOffSwitchContainerBottom: {
    position: "absolute",
    top: "1095px",
    right: "943px",
    width: "150px",
    height: "60px",
    borderRadius: "50px",
    backgroundColor: theme.palette.grey[500],
    display: "flex",
    alignItems: "center",
    padding: theme.spacing(1),
  },
  onOffSwitchLabelBottom: {
    fontWeight: "bold",
    color: theme.palette.grey[700],
    fontSize: "1rem",
    marginLeft: theme.spacing(1),
  },
  startGameButtonBottom: {
    position: "absolute",
    bottom: theme.spacing(4),
    left: "50%",
    transform: "translateX(-50%)",
    marginTop: theme.spacing(4),
    marginBottom: theme.spacing(2),
    width: "250px",
    height: "60px",
    backgroundColor: "black",
    borderRadius: "15px",
    color: "white",
    fontSize: "30px",
    fontWeight: "normal",
    textAlign: "center",
    lineHeight: "60px",
  },
})
);
